#ddev-generated
services:
  solr:
    container_name: ddev-${DDEV_SITENAME}-solr
    image: solr
    restart: "no"
    networks: [default, ddev_default]
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    ports:
      - "8983:8983"
    volumes:
      - .:/mnt/ddev_config
      - ./solr:/var/solr
    command:
      - solr-precreate
    environment:
      VIRTUAL_HOST: $DDEV_HOSTNAME
      SOLR_HOST: ddev-${DDEV_SITENAME}-solr
      SOLR_PORT: 8983
      SOLR_OPTS: -Djute.maxbuffer=50000000
      SOLR_HEAP: 1g
  web:
    links:
      - solr:$DDEV_HOSTNAME
