#ddev-generated
services:
  solr:
    container_name: ddev-${DDEV_SITENAME}-solr
    image: solr
    expose:
      - 8983
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    volumes:
      - .:/mnt/ddev_config
      - ./solr:/var/solr
    command:
      - solr-precreate
    environment:
      SOLR_HOST: ddev-${DDEV_SITENAME}-solr
      SOLR_PORT: 8983
      # The pre-trained OpenNLP models require a much bigger buffer.
      SOLR_OPTS: -Djute.maxbuffer=50000000
      #SOLR_HEAP: 1g
      VIRTUAL_HOST: ${DDEV_HOSTNAME}
      HTTP_EXPOSE: 8983:8983
      HTTPS_EXPOSE: 8943:8983
  web:
    links:
      - solr:solr
