#!/usr/bin/env bash
#ddev-generated
set -e

# Ensure "dev" (or alternate SOLR_CORENAME) core config is always up to date even after the
# core has been created. This does not execute the first time,
# when solr-precreate has not yet run.
CORENAME=${SOLR_CORENAME:-dev}
CONFIGSET=${SOLR_CONFIGSET:-dev}
SCHEMA=${SOLR_SCHEMA:-dev}

if [ -d /var/solr/data/${CORENAME}/conf ]; then
    curl -s -o /dev/null "http://${DDEV_SITENAME}.dev.local:8983/solr/admin/cores?action=CREATE&name=${CORENAME}&configSet=${CONFIGSET}&schema=${SCHEMA}&dataDir=data/"
fi